# Generated by Django 2.2.6 on 2019-10-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='dep_name',
            new_name='company_namee',
        ),
    ]
