# Generated by Django 2.2.6 on 2019-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191016_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='dep_name',
            field=models.CharField(default=2, max_length=100, verbose_name='departman adı'),
            preserve_default=False,
        ),
    ]
