# Generated by Django 2.2.6 on 2019-10-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_departament_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='company_namee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
