# Generated by Django 2.2.6 on 2019-10-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191016_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='company_namee',
            new_name='company',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Adı-Soyadı')),
                ('saatlik_ücreti', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Departament')),
            ],
        ),
    ]
