# Generated by Django 2.0.3 on 2019-10-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191016_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dep_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Departament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
